export default {
  colorDefault: "#505050",
  colorDefaultActive: "#fff",
  colorPrimary: "#246ab9",
  colorPrimaryActive: "#3284e1",
  colorWarning: "#FF9A2A",
  colorSuccess: "#30c557",
  colorError: "#F56C6C",
  colorDisabled: "#ddd",
  textDefaultColor: '#252323',
  textDefaultFontSize: '14px',
  textLgFontSize: '18px',
  backgroundDefaultColor: '#fff',
  backgroundDefaultColorActive: '#e8e8e8',
  bgPrimaryActiveFontColor: '#fff',
};
